name: full_stack_social_app
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.0
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.16
  go_router: ^14.6.2
  google_fonts: ^6.2.1
  stories_for_flutter: ^1.2.1
  flutter_staggered_grid_view: ^0.7.0
  flutter_dotenv: ^5.2.1
  built_collection: ^5.1.1
  built_value: ^8.4.3
  chopper: ^6.1.1
  chopper_built_value: ^1.2.0
  http: ^1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.3.3
  built_value_generator: ^8.4.3
  chopper_generator: ^6.0.0
  analyzer: ^5.13.0  
  flutter_lints: ^5.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    # - assets/images/
#important commands
#flutter version 3.24.4
#flutter packages pub run build_runner build --delete-conflicting-outputs
#flutter build apk --release --no-sound-null-safety
#flutter build apk --split-per-abi --no-sound-null-safety
#flutter run --release --no-sound-null-safety 